version: '2.4'
services:
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.5.4-beta
    networks:
      kafka_net:
        ipv4_address: 172.20.1.10
    expose:
      - 2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.11-1.0.1
#    image: wurstmeister/kafka:2.11-1.1.0
    networks:
      kafka_net:
        ipv4_address: 172.20.1.20
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  cassandra:
    container_name: cassandra
    image: library/cassandra:3.11
    networks:
      kafka_net:
        ipv4_address: 172.20.1.40
# docker exec -ti cassandra /bin/bash
# cqlsh
# CREATE KEYSPACE info WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };

  gateway-service:
    container_name: gateway
    build: gateway-service/build/docker/.
    networks:
      kafka_net:
        ipv4_address: 172.20.1.30

  account-service:
    container_name: account-service
    build: account-service/build/docker/.
    networks:
      kafka_net:
        ipv4_address: 172.20.1.31

  account-service2:
    container_name: account-service2
    build: account-service/build/docker/.
    networks:
      kafka_net:
        ipv4_address: 172.20.1.32

#  beta:
#    container_name: beta
#    build: beta-service/build/docker/.
#    networks:
#      kafka_net:
#        ipv4_address: 172.20.1.33

  config-server:
    container_name: config-server
    build: config-server/build/docker/.
    networks:
      kafka_net:
        ipv4_address: 172.20.1.40

networks:
 kafka_net:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 172.20.1.0/24

# to connect to zookeeper from you local machine edit /etc/hosts and add "172.20.1.10  zookeeper"
# to connect to kafka from you local machine edit /etc/hosts and add "172.20.1.20  kafka"
# to connect to cassandra from you local machine edit /etc/hosts and add "172.20.1.40 cassandra"
