version: '2.1'
services:
 zookeeper:
  container_name: zookeeper
  image: wurstmeister/zookeeper
  networks:
   kafka_net:
    ipv4_address: 172.20.1.10
  expose:
    - 2181

 kafka:
  container_name: kafka
  image: wurstmeister/kafka
  networks:
   kafka_net:
    ipv4_address: 172.20.1.20
  ports:
   - 9092:9092
  environment:
   KAFKA_ADVERTISED_HOST_NAME: kafka
   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#  volumes:
#   - /var/run/docker.sock:/var/run/docker.sock
networks:
 kafka_net:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: 172.20.1.0/24


# to connect to kafka from you local machine edit /etc/hosts and add "172.20.1.20  kafka"
