server:
  port: 8081

spring:
  kafka:
    consumer:
      auto-commit-interval: 100ms
      bootstrap-servers: kafka:9092
      enable-auto-commit: true
      group-id: s1pGroup
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: ch.fuzzle.event.account
  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: kafka
#          zk-nodes: zookeeper
#        streams:
#          binder:
#            configuration:
#              commit.interval.ms: 1000
#              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        account-in:
          contentType: application/json
          destination: account
          consumer:
            header-mode: raw


kafka:
  topics:
    account: account

logging:
  level:
    org.springframework.cloud.zookeeper: INFO