server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka:9092

kafka:
  topics:
    account: account


#spring:
#  data:
#    cassandra:
#      keyspace-name: info
#      schema-action: create_if_not_exists
#      contact-points: cassandra
